# ~~~~~ Day 4 ~~~~~ 
## Part 1

In [1]:
import numpy as np
import math

boards = []
with open('d04.txt', 'r') as f:
    content = f.readlines()

random_numbers = [int(c) for c in content[0].strip('\n').split(',')]

boards = np.zeros(shape=(int(len(content)/6), 5, 5), dtype=int)
chunk_row = 0
board = 0
for row in range(2, len(content)):
    if content[row] != '\n':
        boards[board, chunk_row] = [int(content[row][i:i+3].strip(' ')) for i in range(0, len(content[row]), 3)]
        chunk_row += 1
        if chunk_row > 4:
            chunk_row = 0
            board += 1

boards

array([[[68, 73, 98, 51, 49],
        [82, 56, 87, 64,  8],
        [46,  7, 21, 38, 30],
        [66,  5, 86, 97, 74],
        [60, 63, 76, 55, 39]],

       [[92, 20, 87, 77, 52],
        [72, 29, 81, 24, 64],
        [26, 16, 19, 79, 68],
        [ 8, 53, 90, 14, 74],
        [28, 89, 78, 54, 15]],

       [[13, 17, 35,  2, 85],
        [37, 87, 57, 74, 65],
        [60, 21, 18, 98, 96],
        [ 4, 51, 46, 84,  0],
        [90, 75, 80, 41, 64]],

       ...,

       [[34, 73, 60, 32, 56],
        [49, 35, 44, 79, 83],
        [64, 61, 57,  5, 24],
        [72, 58,  8, 66, 77],
        [94, 31, 55, 67, 74]],

       [[49, 17, 22, 97, 88],
        [ 0, 16, 14, 93, 31],
        [28, 73,  6, 82, 90],
        [80, 45, 92, 55, 78],
        [ 3, 42, 65, 37, 29]],

       [[23, 61, 97,  1, 69],
        [53, 98, 28, 52, 19],
        [66, 51, 46, 77, 15],
        [34, 36, 47, 80, 14],
        [ 7, 89, 62,  9, 49]]])

In [2]:
#draws = np.reshape(random_numbers + ([-1 for i in range(0, math.ceil(len(random_numbers)/5)*5-len(random_numbers))]), (-1, 5))
draws = random_numbers

In [3]:
matches = np.zeros(shape=boards.shape)
winning_board = -1
for i in range(0, len(draws)):
    matches = np.logical_or(matches, np.isin(boards, draws[i]))
    #print(matches)

    h_true = np.alltrue(matches, axis=2)
    if np.any(h_true):
        print(f'Number {i+1}: horizonal all true, position {np.where(h_true)}')
        winning_board = np.where(np.any(h_true, axis=1))[0][0]
        break
    v_true = np.alltrue(matches, axis=1)
    if np.any(v_true):
        print(f'Number {i+1}: vertical all true, position {np.where(v_true)}')
        winning_board = np.where(np.any(v_true, axis=1))[0][0]
        break
    
print(f'Winning board: {winning_board+1}')

Number 16: horizonal all true, position (array([68]), array([4]))
Winning board: 69


In [4]:
print(boards[winning_board])
print(matches[winning_board])
print(boards[winning_board, ~matches[winning_board]])
winsum = np.sum(boards[winning_board, ~matches[winning_board]])
print(f'Winning sum: {winsum}, called number: {draws[i]} -> {winsum*draws[i]}')

[[98 74 36 23  6]
 [65 17 78 95 96]
 [68 63 47 16 18]
 [87 30 53 51 57]
 [69 11 44 75 89]]
[[False False False  True False]
 [False False  True False False]
 [False False False False False]
 [False  True False False False]
 [ True  True  True  True  True]]
[98 74 36  6 65 17 95 96 68 63 47 16 18 87 53 51 57]
Winning sum: 947, called number: 44 -> 41668


## Part 2

In [5]:
matches = np.zeros(shape=boards.shape)
nboards = boards.shape[0]
winning_boards = np.zeros(shape=nboards, dtype=bool)
for i in range(0, len(draws)):
    matches = np.logical_or(matches, np.isin(boards, draws[i]))
    h_true = np.alltrue(matches, axis=2)
    v_true = np.alltrue(matches, axis=1)
    winning_boards = np.logical_or(winning_boards, np.any(h_true, axis=1))
    winning_boards = np.logical_or(winning_boards, np.any(v_true, axis=1))
    if np.sum(winning_boards) == nboards - 1:
        losing_board = np.where(~winning_boards)[0][0]
    if np.sum(winning_boards) == nboards:
        break

In [6]:
print(boards[losing_board])
print(matches[losing_board])
print(boards[losing_board, ~matches[losing_board]])
winsum = np.sum(boards[losing_board, ~matches[losing_board]])
print(f'Winning sum: {winsum}, called number: {draws[i]} -> {winsum*draws[i]}')

[[26 47  2 22  9]
 [ 6 81 53 17 88]
 [58 25 55 31 19]
 [42 27 85 97 14]
 [64 52 66 63 51]]
[[ True  True  True  True False]
 [ True False  True  True  True]
 [False False  True  True  True]
 [ True  True False  True False]
 [ True  True False  True  True]]
[ 9 81 58 25 85 14 66]
Winning sum: 338, called number: 31 -> 10478
